AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Reply greeting, set/clear/show filters'
Resources:
  replyGreeting:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: 'Reply greeting, set/clear/show filters'
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::707614736550:role/lambda-exec-role-for-lex-get-started'
      Environment:
        Variables:
          db_default_collection: macys_shirts
